import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";


const roboto = Roboto({
  subsets: ['latin'],        // Türkçe destek için ['latin', 'latin-ext'] ekleyebilirsin
  weight: ['400', '500', '700'], // Kullanacağın kalınlıklar
  display: 'swap',           // Önerilen ayar
});

export const metadata: Metadata = {
  title: "X, Olan biten burada / X",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        {children}
      </body>
    </html>
  );
}
